import { Author } from './author.interface';
import { CommentAuthor } from './comment.author.interface';
import { PostTerm } from './term.interface';

export const MOCK_POSTS: any[] = [{"id":131,"date":"2017-04-06T05:07:23","date_gmt":"2017-04-06T05:07:23","guid":{"rendered":"http:\/\/devel2.ordermate.online\/2017\/04\/06\/banaue-rice-terraces\/"},"modified":"2017-05-04T23:45:15","modified_gmt":"2017-05-04T23:45:15","slug":"banaue-rice-terraces","status":"publish","type":"post","link":"http:\/\/devel2.ordermate.online\/2017\/04\/06\/banaue-rice-terraces\/","title":{"rendered":"Banaue Rice Terraces"},"content":{"rendered":"<p>The\u00a0<strong><a href=\"https:\/\/en.wikipedia.org\/wiki\/Banaue\">Banaue<\/a>\u00a0Rice Terraces<\/strong>\u00a0(<a href=\"https:\/\/en.wikipedia.org\/wiki\/Filipino_language\">Filipino<\/a>:\u00a0<em>Hagdan-hagdang Palayan ng Banawe<\/em>) are 2,000-year-old\u00a0<a href=\"https:\/\/en.wikipedia.org\/wiki\/Terrace_(agriculture)\">terraces<\/a>\u00a0that were carved into the mountains of\u00a0<a href=\"https:\/\/en.wikipedia.org\/wiki\/Ifugao\">Ifugao<\/a>\u00a0in the\u00a0<a href=\"https:\/\/en.wikipedia.org\/wiki\/Philippines\">Philippines<\/a>\u00a0by ancestors of the\u00a0<a href=\"https:\/\/en.wikipedia.org\/wiki\/Igorot\">indigenous people<\/a>. The Rice Terraces are commonly referred to as the \u201c<a href=\"https:\/\/en.wikipedia.org\/wiki\/Eighth_Wonder_of_the_World\">Eighth Wonder of the World<\/a>\u201c.\u00a0It is commonly thought that the terraces were built with minimal equipment, largely by hand. The terraces are located approximately 1500 metres (5000\u00a0ft) above sea level. They are fed by an ancient\u00a0<a href=\"https:\/\/en.wikipedia.org\/wiki\/Irrigation\">irrigation<\/a>\u00a0system from the rainforests above the terraces. It is said that if the steps were put end to end, it would encircle half the globe.<\/p>\n<p>Locals to this day still plant rice and vegetables on the terraces, although more and more younger Ifugaos do not find farming appealing, often opting for the more lucrative hospitality industry generated by the terraces. The result is the gradual erosion of the characteristic \u201csteps\u201d, which need constant reconstruction and care. In 2010, a further problem was drought, with the terraces drying up completely in March of that year. \u2013 WIKIPEDIA<\/p>\n","protected":false},"excerpt":{"rendered":"<p>The\u00a0Banaue\u00a0Rice Terraces\u00a0(Filipino:\u00a0Hagdan-hagdang Palayan ng Banawe) are 2,000-year-old\u00a0terraces\u00a0that were carved into the mountains of\u00a0Ifugao\u00a0in the\u00a0Philippines\u00a0by ancestors of the\u00a0indigenous people. The Rice Terraces are commonly referred to as the \u201cEighth Wonder of the World\u201c.\u00a0It is commonly thought that the terraces were built with minimal equipment, largely by hand. The terraces are located approximately 1500 metres (5000\u00a0ft) above [&hellip;]<\/p>\n","protected":false},"author":2,"featured_media":130,"comment_status":"open","ping_status":"open","sticky":false,"template":"","format":"standard","meta":[],"categories":[1],"tags":[],"_links":{"self":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/131"}],"collection":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/users\/2"}],"replies":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/comments?post=131"}],"version-history":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/131\/revisions"}],"wp:featuredmedia":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media\/130"}],"wp:attachment":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media?parent=131"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/categories?post=131"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/tags?post=131"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}},
                    {"id":33,"date":"2017-03-13T05:53:43","date_gmt":"2017-03-13T05:53:43","guid":{"rendered":"http:\/\/devel2.ordermate.online\/?p=33"},"modified":"2017-04-05T15:52:37","modified_gmt":"2017-04-05T15:52:37","slug":"teotihuacan","status":"publish","type":"post","link":"http:\/\/devel2.ordermate.online\/2017\/03\/13\/teotihuacan\/","title":{"rendered":"Teotihuacan"},"content":{"rendered":"<p>Teotihuacan was an ancient Mesoamerican city that was established around 100 BC. At one time, it was the largest metropolis in the pre-Columbian Americas and had significant cultural influence on surrounding areas. The Aztecs named the region Teotihuacan (&ldquo;the place where gods were created&rdquo;) when they arrived centuries after its fall. Here, you can walk along the Avenue of the Dead, Teotihuacan&rsquo;s main road. The broad, central thoroughfare dissects the city and is surrounded by mounds that resemble large tombs. Tourists can view a number of well-preserved murals, as well as the Pyramid of the Moon and the Pyramid of the Sun. The latter is the third largest pyramid in the world. Teotihuacan became a UNESCO World Heritage Site in 1987.<\/p>\n","protected":false},"excerpt":{"rendered":"<p>Teotihuacan was an ancient Mesoamerican city that was established around 100 BC. At one time, it was the largest metropolis in the pre-Columbian Americas and had significant cultural influence on surrounding areas. The Aztecs named the region Teotihuacan (&ldquo;the place where gods were created&rdquo;) when they arrived centuries after its fall. Here, you can walk [&hellip;]<\/p>\n","protected":false},"author":1,"featured_media":34,"comment_status":"open","ping_status":"open","sticky":false,"template":"","format":"image","meta":[],"categories":[5],"tags":[3,14],"_links":{"self":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/33"}],"collection":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/comments?post=33"}],"version-history":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/33\/revisions"}],"wp:featuredmedia":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media\/34"}],"wp:attachment":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media?parent=33"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/categories?post=33"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/tags?post=33"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}},
                    {"id":30,"date":"2017-02-24T05:52:28","date_gmt":"2017-02-24T05:52:28","guid":{"rendered":"http:\/\/devel2.ordermate.online\/?p=30"},"modified":"2017-02-24T06:17:19","modified_gmt":"2017-02-24T06:17:19","slug":"taj-mahal","status":"publish","type":"post","link":"http:\/\/devel2.ordermate.online\/2017\/02\/24\/taj-mahal\/","title":{"rendered":"Taj Mahal"},"content":{"rendered":"<p>An architectural love letter, this massive marble temple in northern India is one of the most recognizable structures on the planet. It was built in the first half of the 17th century by Mughal emperor Shah Jahan to hold the body of his beloved third wife, Mumtaz Mahal (the building is now a mausoleum for both). The construction took more than 22 years to complete, requiring as many as 20,000 workers. Some skilled artisans came from as far as Constantinople (today, Istanbul), and about 1,000 elephants were used to transport materials. Today, vehicles that emit pollution are not allowed within a mile of the structure, so be prepared to walk or hire a battery-powered vehicle called a tuk tuk.<\/p>\n","protected":false},"excerpt":{"rendered":"<p>An architectural love letter, this massive marble temple in northern India is one of the most recognizable structures on the planet. It was built in the first half of the 17th century by Mughal emperor Shah Jahan to hold the body of his beloved third wife, Mumtaz Mahal (the building is now a mausoleum for [&hellip;]<\/p>\n","protected":false},"author":1,"featured_media":31,"comment_status":"open","ping_status":"open","sticky":false,"template":"","format":"image","meta":[],"categories":[5],"tags":[13,3],"_links":{"self":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/30"}],"collection":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/comments?post=30"}],"version-history":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/30\/revisions"}],"wp:featuredmedia":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media\/31"}],"wp:attachment":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media?parent=30"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/categories?post=30"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/tags?post=30"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}},
                    {"id":21,"date":"2017-02-24T05:46:00","date_gmt":"2017-02-24T05:46:00","guid":{"rendered":"http:\/\/devel2.ordermate.online\/?p=21"},"modified":"2017-03-30T10:13:20","modified_gmt":"2017-03-30T10:13:20","slug":"iguazu-falls","status":"publish","type":"post","link":"http:\/\/devel2.ordermate.online\/2017\/02\/24\/iguazu-falls\/","title":{"rendered":"Iguazu Falls"},"content":{"rendered":"<p>Iguaz\u00fa National Park, situated on the international border of Argentina and Brazil, features one of the world\u2019s most striking natural wonders. Iguaz\u00fa Falls offers a misty and majestic realm of rushing, roaring water with rainbows adorning the cascades, which stretch for nearly 2 miles. Experience this marvel up close from one of the wooden walkways that stretch out over the river, and be sure to take in the spectacular vista from the giant balcony of the \u201cDevil\u2019s Throat.\u201d According to ancient myths, a jealous god slashed the Iguaz\u00fa River (meaning \u201cgreat water\u201d) in two, creating falls as high as 269 feet. The UNESCO site is bordered by its sister park Igua\u00e7u in Brazil, and the falls are surrounded by the lush Misiones rainforest, so don\u2019t be surprised to see tropical birds flitting about as they search for fish in quieter waters.<\/p>\n","protected":false},"excerpt":{"rendered":"<p>Iguaz\u00fa National Park, situated on the international border of Argentina and Brazil, features one of the world\u2019s most striking natural wonders. Iguaz\u00fa Falls offers a misty and majestic realm of rushing, roaring water with rainbows adorning the cascades, which stretch for nearly 2 miles. Experience this marvel up close from one of the wooden walkways [&hellip;]<\/p>\n","protected":false},"author":1,"featured_media":22,"comment_status":"open","ping_status":"open","sticky":false,"template":"","format":"standard","meta":[],"categories":[5],"tags":[10,3],"_links":{"self":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/21"}],"collection":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/comments?post=21"}],"version-history":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/21\/revisions"}],"wp:featuredmedia":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media\/22"}],"wp:attachment":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media?parent=21"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/categories?post=21"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/tags?post=21"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}},
                    {"id":14,"date":"2017-02-24T05:42:22","date_gmt":"2017-02-24T05:42:22","guid":{"rendered":"http:\/\/devel2.ordermate.online\/?p=14"},"modified":"2017-03-30T10:12:48","modified_gmt":"2017-03-30T10:12:48","slug":"grand-canyon","status":"publish","type":"post","link":"http:\/\/devel2.ordermate.online\/2017\/02\/24\/grand-canyon\/","title":{"rendered":"Grand Canyon"},"content":{"rendered":"<p>If North America\u2019s greatest natural wonder \u2014 a red-hued canyon 277 river miles long, 18 miles wide, and one mile deep \u2014 doesn\u2019t make your mouth drop in awe, then you might not be human. While the north rim attracts fewer visitors, you\u2019ll most likely appreciate the epic vistas of the south rim. There are plenty of spots to pull the car over and have a look from the top, but we recommend trekking along the rim on foot. You can also descend into the canyon\u2019s depths via mules or guided hiking excursions, experience \u201cThe Heart of the Canyon\u201d by raft on the Colorado River and even spend the night at a lodge below the rim.<\/p>\n","protected":false},"excerpt":{"rendered":"<p>If North America\u2019s greatest natural wonder \u2014 a red-hued canyon 277 river miles long, 18 miles wide, and one mile deep \u2014 doesn\u2019t make your mouth drop in awe, then you might not be human. While the north rim attracts fewer visitors, you\u2019ll most likely appreciate the epic vistas of the south rim. There are [&hellip;]<\/p>\n","protected":false},"author":1,"featured_media":15,"comment_status":"open","ping_status":"open","sticky":false,"template":"","format":"image","meta":[],"categories":[5],"tags":[3,8],"_links":{"self":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/14"}],"collection":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/comments?post=14"}],"version-history":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/14\/revisions"}],"wp:featuredmedia":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media\/15"}],"wp:attachment":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media?parent=14"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/categories?post=14"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/tags?post=14"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}},
                    {"id":11,"date":"2017-02-24T05:40:12","date_gmt":"2017-02-24T05:40:12","guid":{"rendered":"http:\/\/devel2.ordermate.online\/?p=11"},"modified":"2017-03-30T10:12:25","modified_gmt":"2017-03-30T10:12:25","slug":"galapagos-islands","status":"publish","type":"post","link":"http:\/\/devel2.ordermate.online\/2017\/02\/24\/galapagos-islands\/","title":{"rendered":"Galapagos Islands"},"content":{"rendered":"<p>Located some 600 miles off the South American coast, this Ecuadorian archipelago has been drawing nature-lovers to its remote shores ever since naturalist and geologist Charles Darwin explored the islands in 1835. A one-time outpost of pirates and prisoners, the Gal\u00e1pagos Islands are also home to an incredibly diverse collection of flora and fauna, including many species \u2014 such as the Gal\u00e1pagos giant tortoise and marine iguana \u2014 that can be found nowhere else on Earth. Today, 97 percent of the archipelago\u2019s land area is protected by a national park. Visitors can get up-close-and-personal with wildlife on guided boat tours, scuba expeditions and hikes, where curious creatures often approach sightseers without hesitation.<\/p>\n","protected":false},"excerpt":{"rendered":"<p>Located some 600 miles off the South American coast, this Ecuadorian archipelago has been drawing nature-lovers to its remote shores ever since naturalist and geologist Charles Darwin explored the islands in 1835. A one-time outpost of pirates and prisoners, the Gal\u00e1pagos Islands are also home to an incredibly diverse collection of flora and fauna, including [&hellip;]<\/p>\n","protected":false},"author":1,"featured_media":12,"comment_status":"open","ping_status":"open","sticky":false,"template":"","format":"image","meta":[],"categories":[5],"tags":[6,7,3],"_links":{"self":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/11"}],"collection":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/comments?post=11"}],"version-history":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/11\/revisions"}],"wp:featuredmedia":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media\/12"}],"wp:attachment":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media?parent=11"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/categories?post=11"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/tags?post=11"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}},
                    {"id":4,"date":"2017-02-23T23:47:03","date_gmt":"2017-02-23T23:47:03","guid":{"rendered":"http:\/\/devel.ordermate.online\/wordpress\/?p=4"},"modified":"2017-04-11T23:22:53","modified_gmt":"2017-04-11T23:22:53","slug":"angkor-wat","status":"publish","type":"post","link":"http:\/\/devel2.ordermate.online\/2017\/02\/23\/angkor-wat\/","title":{"rendered":"Angkor Wat."},"content":{"rendered":"<p>Built by Khmer King Suryavarman II in the first half of the 12th century, Angkor Wat was one of the most significant architectural achievements of ancient times, and remains the world\u2019s largest religious monument today. The sprawling Cambodian temple complex is a source of national pride and international renown thanks to its distinctive sandstone spires, intricate artistry and massive moat that encloses the grounds in a three-and-a-half-mile perimeter. First dedicated to Vishnu as a Hindu temple and later a center of Theravada Buddhism, the well-preserved site is one of more than 1,000 temples in the Angkor area, many of which are easily accessible from nearby Siem Reap<\/p>\n","protected":false},"excerpt":{"rendered":"<p>Built by Khmer King Suryavarman II in the first half of the 12th century, Angkor Wat was one of the most significant architectural achievements of ancient times, and remains the world\u2019s largest religious monument today. The sprawling Cambodian temple complex is a source of national pride and international renown thanks to its distinctive sandstone spires, [&hellip;]<\/p>\n","protected":false},"author":1,"featured_media":8,"comment_status":"open","ping_status":"open","sticky":false,"template":"","format":"image","meta":[],"categories":[5],"tags":[4,3],"_links":{"self":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/4"}],"collection":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/comments?post=4"}],"version-history":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/4\/revisions"}],"wp:featuredmedia":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media\/8"}],"wp:attachment":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media?parent=4"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/categories?post=4"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/tags?post=4"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}},
                    {"id":18,"date":"2017-02-15T05:44:34","date_gmt":"2017-02-15T05:44:34","guid":{"rendered":"http:\/\/devel2.ordermate.online\/?p=18"},"modified":"2017-03-21T05:00:12","modified_gmt":"2017-03-21T05:00:12","slug":"great-wall-of-china","status":"publish","type":"post","link":"http:\/\/devel2.ordermate.online\/2017\/02\/15\/great-wall-of-china\/","title":{"rendered":"Great Wall of China"},"content":{"rendered":"<p>The Great Wall of China is the largest cultural relic humans have ever built and is the only man-made structure that is visible from space. It snakes through China ever so majestically, around undulating hills and through a vast countryside, stretching from Shanhaiguan in the east to Lop Lake in the west. Wall construction began more than 2,000 years ago in an attempt to keep out the tribes from the north. This landmark is thousands of miles long, passes through 156 counties, with 7,062 lookout towers. The most colorful (and least costly) times to go are spring and autumn \u2014 pink cherry blossoms blanket the landscape outside of Beijing in late-March, and in mid-October red leaves abound near Badaling National Forest Park.<\/p>\n","protected":false},"excerpt":{"rendered":"<p>The Great Wall of China is the largest cultural relic humans have ever built and is the only man-made structure that is visible from space. It snakes through China ever so majestically, around undulating hills and through a vast countryside, stretching from Shanhaiguan in the east to Lop Lake in the west. Wall construction began [&hellip;]<\/p>\n","protected":false},"author":1,"featured_media":19,"comment_status":"open","ping_status":"open","sticky":false,"template":"","format":"image","meta":[],"categories":[5],"tags":[9,3],"_links":{"self":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/18"}],"collection":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/comments?post=18"}],"version-history":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/18\/revisions"}],"wp:featuredmedia":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media\/19"}],"wp:attachment":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media?parent=18"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/categories?post=18"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/tags?post=18"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}},
                    {"id":36,"date":"2017-02-02T05:54:47","date_gmt":"2017-02-02T05:54:47","guid":{"rendered":"http:\/\/devel2.ordermate.online\/?p=36"},"modified":"2017-05-05T00:15:13","modified_gmt":"2017-05-05T00:15:13","slug":"uluru","status":"publish","type":"post","link":"http:\/\/devel2.ordermate.online\/2017\/02\/02\/uluru\/","title":{"rendered":"Uluru"},"content":{"rendered":"<p>A World Heritage Site, Uluru is an awe-inspiring sandstone rock formation rising out of the desolate outback of Australia\u2019s Northern Territory. The name derives from the aboriginal tribes that settled in the area 10,000 years ago. The landmark is also known as Ayers Rock, named in honor of Sir Henry Ayers, who served as Chief Secretary of South Australia in the late 19th century. Jutting nearly 1,150 feet in the air, the natural monolith is taller than the Eiffel Tower, and stands in stark contrast to the miles of flat desert that surround it. Visitors can climb to the top of Uluru (the hike takes anywhere from 30 minutes to two hours) and explore the base, which is about six miles around. The view atop the rock is remarkable during sunrise and sunset.<\/p>\n","protected":false},"excerpt":{"rendered":"<p>A World Heritage Site, Uluru is an awe-inspiring sandstone rock formation rising out of the desolate outback of Australia\u2019s Northern Territory. The name derives from the aboriginal tribes that settled in the area 10,000 years ago. The landmark is also known as Ayers Rock, named in honor of Sir Henry Ayers, who served as Chief [&hellip;]<\/p>\n","protected":false},"author":1,"featured_media":37,"comment_status":"open","ping_status":"open","sticky":false,"template":"","format":"image","meta":[],"categories":[5],"tags":[15,3],"_links":{"self":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/36"}],"collection":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/comments?post=36"}],"version-history":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/36\/revisions"}],"wp:featuredmedia":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media\/37"}],"wp:attachment":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media?parent=36"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/categories?post=36"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/tags?post=36"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}},
                    {"id":27,"date":"2017-01-24T05:50:14","date_gmt":"2017-01-24T05:50:14","guid":{"rendered":"http:\/\/devel2.ordermate.online\/?p=27"},"modified":"2017-03-21T04:57:10","modified_gmt":"2017-03-21T04:57:10","slug":"pyramids-of-giza","status":"publish","type":"post","link":"http:\/\/devel2.ordermate.online\/2017\/01\/24\/pyramids-of-giza\/","title":{"rendered":"Pyramids of Giza"},"content":{"rendered":"<p>Like Stonehenge, many mysteries surround the construction of these three pyramids, which are part of a mausoleum complex. The Great Pyramid of Giza, the best-known of the group standing outside of Cairo, is the only one of the ancient Seven Wonders of the World that also graces our list. Finished around 2,560 BC, the 481-foot creation (now shorter due to erosion) was the tallest man-made structure in the world for 38 centuries until the completion of Lincoln Cathedral in 14th-century England. How were these made? Were space aliens needed to cut, move and stack the millions of stones, some weighing 88 tons? Does some powerful force emanate from them today? Hop on a camel or hail a taxi and go judge for yourself.<\/p>\n","protected":false},"excerpt":{"rendered":"<p>Like Stonehenge, many mysteries surround the construction of these three pyramids, which are part of a mausoleum complex. The Great Pyramid of Giza, the best-known of the group standing outside of Cairo, is the only one of the ancient Seven Wonders of the World that also graces our list. Finished around 2,560 BC, the 481-foot [&hellip;]<\/p>\n","protected":false},"author":1,"featured_media":28,"comment_status":"open","ping_status":"open","sticky":false,"template":"","format":"image","meta":[],"categories":[5],"tags":[12,3],"_links":{"self":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/27"}],"collection":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/comments?post=27"}],"version-history":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/posts\/27\/revisions"}],"wp:featuredmedia":[{"embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media\/28"}],"wp:attachment":[{"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/media?parent=27"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/categories?post=27"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/devel2.ordermate.online\/wp-json\/wp\/v2\/tags?post=27"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}}]

export class ProxyPost {

    private _id: number;
    get Id(): number {
        return this._id;
    }
    set Id(val: number) {
        this._id = val;
    }

    /*
    private _author: number;
    get Author(): number {
        return this._author;
    }
    set Author(val:number) {
        this._author = val;
    }

    private _categories: number[];
    get Categories(): number[] {
        return this._categories;
    }
    set Categories(val:number[]) {
        this._categories = val;
    }
    */
    private _comment_status: string;
    get Comment_status(): string {
        return this._comment_status;
    }
    set Comment_status(val:string) {
        this._comment_status = val;
    }

    private _content: string;
    get Content(): string {
        return this._content;
    }
    set Content(val:string) {
        this._content = val;
    }

    private _date: string;
    get Date(): string {
        return this._date;
    }
    set Date(val:string) {
        this._date = val;
    }

    private _date_gmt: string;
    get Date_gmt(): string {
        return this._date_gmt;
    }
    set Date_gmt(val:string) {
        this._date_gmt = val;
    }

    private _excerpt: string;
    get Excerpt(): string {
        return this._excerpt;
    }
    set Excerpt(val:string) {
        this._excerpt = val;
    }

    /*
    private _featured_media: number;
    get Featured_media(): number {
        return this._featured_media;
    }
    set Featured_media(val:number) {
        this._featured_media = val;
    }
    */

    private _link: string;
    get Link(): string {
        return this._link;
    }
    set Link(val:string) {
        this._link = val;
    }

    /*
    private _modified_date: Date;
    get Modified_date(): Date {
        return this._modified_date;
    }
    set Modified_date(val:Date) {
        this._modified_date = val;
    }

    private _modified_date_gmt: Date;
    get Modified_date_gmt(): Date {
        return this._modified_date_gmt;
    }
    set Modified_date_gmt(val:Date) {
        this._modified_date_gmt = val;
    }
    */

    private _title: string;
    get Title(): string {
        return this._title;
    }
    set Title(val:string) {
        this._title = val;
    }

    private _embedded_authors: Author[];
    get Embedded_authors(): Author[] {
        return this._embedded_authors;
    }
    set Embedded_authors(val: Author[]) {
        this._embedded_authors = val;
    }

    private _embedded_comments: CommentAuthor[];
    get Embedded_comments(): CommentAuthor[] {
        return this._embedded_comments;
    }
    set Embedded_comments(val: CommentAuthor[]) {
        this._embedded_comments = val;
    }

    private _embedded_featured_medias: any[];
    get Embedded_featured_medias(): any[] {
        return this._embedded_featured_medias;
    }
    set Embedded_featured_medias(val: any[]) {
        this._embedded_featured_medias = val;
    }
    
    private _embedded_terms: any[];
    set Embedded_terms(val: any[]) {
        this._embedded_terms = val;
    }
    get Embedded_terms_category(): PostTerm[] {
        let retVal: PostTerm[];

        if(this._embedded_terms && this._embedded_terms.length > 0) {
            for(let items of this._embedded_terms) {
                if(items.length == 0) continue;

                if((<PostTerm>items[0]).taxonomy == "category") {
                    retVal = items;
                    break;
                }
            }
        }

        return retVal;
    }
    get Embedded_terms_tag(): PostTerm[] {
        let retVal: PostTerm[];

        if(this._embedded_terms && this._embedded_terms.length > 0) {
            for(let items of this._embedded_terms) {
                if(items.length == 0) continue;

                if((<PostTerm>items[0]).taxonomy == "post_tag") {
                    retVal = items;
                    break;
                }
            }
        }

        return retVal;
    }

    private _links_replies: string;
    get Links_replies(): string {
        return this._links_replies;
    }
    set Links_replies(val: string) {
        this._links_replies = val;
    }
    

    /**
     * Handles Post json to convert attributes to an easier to use format
     */
    static fromJson(jsonObject:any): ProxyPost {
        let retVal: ProxyPost = new ProxyPost();

        retVal.Id = jsonObject.id;
        retVal.Comment_status = jsonObject.comment_status;
        retVal.Content = jsonObject.content.rendered;
        retVal.Date = jsonObject.date;
        retVal.Date_gmt = jsonObject.date_gmt;
        retVal.Excerpt = jsonObject.excerpt.rendered;
        retVal.Link = jsonObject.link;
        retVal.Title = jsonObject.title.rendered;
        
        if(jsonObject._embedded) {
            retVal.Embedded_authors = jsonObject._embedded['author'];
            retVal.Embedded_comments = jsonObject._embedded['replies'][0];
            retVal.Embedded_featured_medias = jsonObject._embedded['wp:featuredmedia'];
            retVal.Embedded_terms = jsonObject._embedded['wp:term'];
        }

        if(jsonObject._links) {
            retVal.Links_replies = jsonObject._links['replies'][0].href;
        }
        return retVal;
    }
}